//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Amirhanov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public int HistoryID { get; set; }
        public int TaskID { get; set; }
        public System.DateTime ChangedOn { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public string ChangeDescription { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Tasks Tasks { get; set; }
    }
}
