//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KR2_Amirhanov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tasks()
        {
            this.TaskHistory = new HashSet<TaskHistory>();
        }
    
        public int TaskID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Status { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<int> AssignedToEmployeeID { get; set; }
        public Nullable<int> OrderID { get; set; }
    
        public virtual Departments Departments { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Orders Orders { get; set; }
        public virtual TaskCategories TaskCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskHistory> TaskHistory { get; set; }
        public virtual TaskPriorities TaskPriorities { get; set; }
    }
}
